In [81]:
from exclusiveAI.components.Initializers.Uniform import Uniform
import numpy as np


initializer = Uniform(low=0, high=0.05)
shape = (3, 4)
weights = np.array(initializer.initialize(shape=shape)).astype(np.float32)


print(weights)

[[0.04990866 0.04306795 0.00421157 0.00220168]
 [0.0199001  0.04495613 0.02387814 0.02801051]
 [0.00943388 0.03722873 0.03108962 0.03729112]]
